Modified for Thread Safety
johankson/TinyPubSub pull request #23
Opened 2018-01-30 20:20 UTC by ErikRBergman

* Modified TinyPubSub for thread safety.
* .NET Standard version moved from 1.0 to 1.1.

2018-02-09 06:58 UTC, johankson requested changes
Looks good. Look through the comments if you want to address the issues, otherwise I'll approve this PR.

2018-02-09 06:58 UTC, johankson commented on src/TinyPubSub/TinyPubSub.cs
> +        // EB: Rename to CreateAndAdd?
Rename ok

2018-02-09 06:58 UTC, johankson commented on src/TinyPubSub/TinyPubSub.cs
> +        // EB: Rename to CreateAndAdd?
Rename ok

2018-02-09 06:58 UTC, johankson commented on src/TinyPubSub/TinyPubSub.cs
> +            //// EB: Configure await is only required when awaiting a task, not creating a fire and forget task
Thanks for sharing knowledge, did not now that.

2018-02-09 06:58 UTC, johankson commented on src/TinyPubSub/TinyPubSub.cs
> +            //// TODO: EB: Move the reflection code to a separate type, for performance - add a cache (ConcurrentDictionary) to scanned objects and use expressions to invoke the subscriber methods in
Good point, add it as an issue?

2018-02-09 08:24 UTC, ErikRBergman commented
I guess the "issues" can be addressed later on. The weak reference PR is based on this one, so to avoid merging I propose they are changed later.

2018-02-10 11:14 UTC, johankson approved these changes

2018-02-10 11:14 UTC, merged